### ISSUE TITLE
CustomCNN.conv6( ) is not defined

### ISSUE THREAD

**Issue by rohitdwivedula** [yilingjia/TreeCNN-for-Energy-Breakdown#2]
On line 41 of the `cnn-tree.py` file, you have the statement `e4 = self.conv6(e3)`, but `CustomTree.conv6( )` is not defined anywhere. 

I played around with the code a bit so line numbers will be off, but this is the output on the terminal: 

```
$ python3 cnn-tree.py 1 0.001 500 0 fridge hvac
1 0 0.001 500 0 ['fridge', 'hvac']
NUM ITERATIONS:  500
Traceback (most recent call last):
  File "cnn-tree.py", line 281, in <module>
    fold_num, lr, 0)
  File "cnn-tree.py", line 146, in disagg_fold
    pred = model(*params)
  File "/home/user/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "cnn-tree.py", line 66, in forward
    self.preds[appliance] = getattr(self, "Appliance_" + str(appliance))(agg_current)
  File "/home/user/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "cnn-tree.py", line 41, in forward
    e4 = self.conv6(e3)
  File "/home/user/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 591, in __getattr__
    type(self).__name__, name))
AttributeError: 'CustomCNN' object has no attribute 'conv6'
```

**Comment by rohitdwivedula** [comment]
Another error on line 100: 
```
    train, test = get_train_test(dataset, num_folds=num_folds, fold_num=fold_num)
```

`num_folds` is not defined anywhere else in the file causing a NameError.
